name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    env:
      CI: true
      NODE_ENV: test
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      MCP_CONFIG_PATH: ./config/test.json

    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - name: Test
        run: npm run test:ci
        
      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: |
            test-report/
            coverage/

  test-install:
    needs: build-and-test
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - name: Test global installation
        run: |
          npm pack
          sudo npm install -g ./*.tgz
          mcp-neurolora --help
